### PR TITLE
QE-2205 Licensor update in LICENSE file

### PR DESCRIPTION
**Pull request by mlabuda**
We are missing Licensor and year in license file, this PR is addressing it.

### CODE REVIEW

**Review by lorenbuhle — APPROVED** [review]

**Comment by mlabuda** [comment]
@cygnil could you please merge the PR? I am not authorized to do it.

**Comment by cygnil** [comment]
@mlabuda Do we have a QE ticket number to include in the commit message? Right now it says "QE-XXXX"

**Comment by mlabuda** [comment]
Nope, there is no ticket, I will create if you want to have a record and track PR-issue connection.

**Comment by mlabuda** [comment]
Updated ticket name as well as commit message and provided ref to ticket in JIRA.

**Pull request merged**
